main: ml.chriscommunity.survivalplus.main.Main
name: "SurvivalPlus"
author: GhostlyGames41
version: 1.0
api-version: 1.15
depend: [EconomyPlus]

commands:
   coin:
      usage: /<command>
   rtp:
      usage: /<command>
   shop:
      usage: /<command>
   customize:
   survivalplus:
      aliases: [sp]